name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          automate_autocam_pull.bat
#          cd C:\Users\Meu Computador\Documents\Projects\teste_nykoni\test-transactions
#          type nul > texte_nykolau.txt
#          ${{ secrets.SCRIPT }}
#          php artisan migrate
#          php artisan route:clear
#          php artisan cache:clear
          
