name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/Documents/Projects/teste_nykoni/test-transactions
          ${{ secrets.SCRIPT}}
          php artisan migrate
          php artisan route:clear
          php artisan cache:clear
